# Generated by Django 4.1.7 on 2023-07-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='sign',
            field=models.FileField(default='path/to/default/sign.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='photo',
            field=models.FileField(default='path/to/default/sign.jpg', upload_to='upload/'),
        ),
    ]
