# Generated by Django 4.1.7 on 2023-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_studentdata_sign_alter_studentdata_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='photo',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='sign',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
