# Generated by Django 4.1.7 on 2023-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_alter_studentdata_photo_alter_studentdata_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='pincode',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='year10',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='year12',
            field=models.CharField(max_length=40),
        ),
    ]
