# Generated by Django 4.1.7 on 2023-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_studentdata_pincode_alter_studentdata_year10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
