# Generated by Django 4.1.7 on 2023-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_alter_studentdata_pincode_alter_studentdata_year10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
